### ISSUE TITLE
Application resources missing attributes since 0.10.0

### ISSUE THREAD

**Issue by twendt** [terraform-providers/terraform-provider-azuread#319] opened 2020-09-17 20:24 UTC
The application resource used to have all the attributes exported, but this has changed since 0.10.0.  Since then it only has the application_id and object_id. The data source still has all the attributes available.

It seems to have happened with PR 252.

Has this happened on purpose? It is breaking my deployment and so far kept me from upgrading to later versions.

**Comment by manicminer** [comment] 2020-09-17 21:27
Hi @twendt, can you expand on which attributes are missing? Since you linked #252 I suspect this may be a duplicate of #265 - if that's the case there in a workaround in that issue that involves using a `for` statement to construct a list of `oauth2_permissions`.

If you are referencing specific permissions from an application, you might consider using the [azuread_application_oauth2_permission](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_oauth2_permission) resource instead which will give you a simpler configuration.

**Comment by twendt** [comment] 2020-09-18 12:54
You are right I was actually having the issue with the `oauth2_permission`. Sorry, I haven't seen #265 

I was thinking that there were more attributes existing up to 0.9.0, but I just checked the old documentation and it was really just the `oauth2_permission` that was deleted from the attributes. I will see if I can move to the new resource. It might break my existing deployments though.

**Comment by manicminer** [comment] 2020-09-21 07:52
@twendt Thanks for confirming. It's not that the attribute was removed - it changed from a list to a set because the ordering is not consistent. I'm going to go ahead and close this issue for now. Please feel fre to open another issue if you have any problem not covered in #265.

**Comment by manicminer** [comment] 2020-09-21 07:52
Duplicate of #265

**Closed by manicminer** 2020-09-21 07:52 UTC
Labels: bug, feature/application
