### ISSUE TITLE
Support for self-signed certs and Key Vault storage when creating a service principal

### ISSUE THREAD

**Issue by erick-thompson** [terraform-providers/terraform-provider-azuread#38] opened 2019-02-11 21:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have some configuration scripts I am converting to terraform. One of them uses the az cli command

`az ad sp create-for-rbac --name $servicePrincipalName --create-cert --cert $servicePrincipalName --keyvault serviceprincipal-creds --skip-assignment true`

The advantage of using this is that the certificate for the service principal is stored in key vault and so can be used from there in other scripts and deployments. It appears that the current version does not support certificates, with or without key vault. 

Any chance this could be implemented? 

### New or Affected Resource(s)

* azuread_service_principal

### Potential Terraform Configuration

Not sure how this would look, given that it combines key vault and Azure AD

### References

https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest

**Comment by katbyte** [comment] 2019-05-23 23:32
Hi @erick-thompson,

This looks like a duplicate of #29. As such i am going to close it in favour of the older issue. If you think i've closed this in error please reopen it!

**Closed by katbyte** 2019-05-23 23:32 UTC
Labels: enhancement, feature/service-principal
