### ISSUE TITLE
No-subscriber support does not work since 0.11.0

### ISSUE THREAD

**Issue by trajano** [terraform-providers/terraform-provider-azuread#325] opened 2020-09-28 21:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
$ terraform -v
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azuread v0.10.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
```

### Affected Resource(s)

* N/A it's the provider

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azuread = {
      source = "hashicorp/azuread"
      version = "0.10.0"
    }
    random = {
      source = "hashicorp/random"
      version = "~> 2.3.0"
    }
  }
  required_version = ">= 0.13"
}

provider "azuread" {
  tenant_id = "XXXXXX-XXXX-XXXX-XXXX-XXXXX"
  subscription_id = "" # this works with 0.10.0 but not 0.11.0 nor 1.0.0
  environment     = "public"
}

provider "random" {
  
}
```

### Expected Behavior

No issues

### Actual Behavior

```
Error: Unsupported argument

  on provider.tf line 4, in provider "azuread":
   4:   subscription_id = "XXXX" 
# where XXXX was blank or copied from the tenant ID
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

**UPDATE** I log in initially with `az login` or `az login --allow-no-subscriptions`

### References

* #0000

**Comment by manicminer** [comment] 2020-09-30 06:06
@trajano `subscription_id` is no longer a supported provider configuration value. Have you tried omitting it?

e.g.
```hcl
provider "azuread" {
  tenant_id = "XXXXXX-XXXX-XXXX-XXXX-XXXXX"
  environment     = "public"
}
```

**Comment by trajano** [comment] 2020-09-30 11:41
Yes Error: building AzureAD Client: obtain subscription(XXXXX-XXXXXXX) from Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1  From: 'Tom Bamford' via Open Source DevelopmentSent: September 30, 2020 2:06 AMTo: terraform-providers/terraform-provider-azureadCc: Archimedes Trajano; MentionSubject: Re: [terraform-providers/terraform-provider-azuread] No-subscriber support does not work since 0.11.0 (#325) @trajano subscription_id is no longer a supported provider configuration value. Have you tried omitting it?e.g.provider "azuread" {  tenant_id = "XXXXXX-XXXX-XXXX-XXXX-XXXXX"  environment     = "public"}—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by manicminer** [comment] 2020-09-30 15:56
Ah ok, you didn't mention you are using CLI authentication. There's an existing issue #314 with a potential workaround, but as explained, some recent changes to Azure CLI are possibly incompatible with subscription-less scenarios for some people.

**Comment by manicminer** [comment] 2020-10-05 12:23
Duplicate of #314

**Closed by manicminer** 2020-10-05 12:23 UTC
Labels: provider, question
