### ISSUE TITLE
Group membership not able to update dynamically using terraform

### ISSUE THREAD

**Issue by pawankmr301** [terraform-providers/terraform-provider-azuread#233] opened 2020-03-31 10:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by katbyte** [comment] 2020-05-15 03:58
Hi @pawankmr301,

I'm not sure what the issue is here as none of the requested information has been filled out. I'm going to close this but please do open a new issue with more information describing what the problem is. Thanks!

**Closed by katbyte** 2020-05-15 03:58 UTC
