### ISSUE TITLE
Ability to manipulate Owners on azuread_application resources

### ISSUE THREAD

**Issue by dekimsey** [terraform-providers/terraform-provider-azuread#46] opened 2019-02-15 18:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When working on a shared state, after an azuread_application resource is created I have to jump into the Azure console to add my teammates as Owners. Otherwise they will receive an access denied error when using it.

### New or Affected Resource(s)

* azuread_application

### Potential Terraform Configuration

Unsure, maybe a resource per-owner vs a resource encompassing all owners?

```hcl
resource "azuread_application_owners" "my-app" {
  application_id = "${azuread_application.my-app.application_id}"
  users = ["..."]
}

resource "azuread_application_owner" "my-app_bob" {
  application_id = "${azuread_application.my-app.application_id}"
  user_id = "${bobs_id}"
}
```

### References

Error message from a co-workers recently added resource:
```
$ terraform apply
...
* azuread_application.my-app: Error patching Azure AD Application with ID "9cfdc4b1-ff1d-421c-be22-2125f1f0349d": graphrbac.ApplicationsClient#Patch: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2019-02-15T17:26:29","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"1431185e-3a31-4e57-b37c-4633949765a8"}}]
```

**Comment by vanhove** [comment] 2019-04-23 17:36
This would be a nice feature to have

**Comment by katbyte** [comment] 2019-05-23 23:15
Closing as a duplicate of #36 @vanhove, @dekimsey 

There is also an open PR adding this functionality: #62

**Closed by katbyte** 2019-05-23 23:15 UTC
Labels: enhancement, new-resource
