### ISSUE TITLE
Cannot Reference azuread_application.oauth_permissions[0] in setting required_resource_action

### ISSUE THREAD

**Issue by jalleyne** [terraform-providers/terraform-provider-azuread#272] opened 2020-06-11 20:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.12.26
+ provider.azuread v0.9.0
+ provider.azurerm v2.2.0
+ provider.helm v1.1.1
+ provider.kubernetes v1.11.3
+ provider.random v2.2.1

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp


resource "azuread_application" "aks_server" {
  name = "${var.resource_group_name}-aks-server-adapp"
  identifier_uris = [
    "https://${var.resource_group_name}-aks-server-sp"
  ]
  reply_urls = [
    "https://${var.resource_group_name}-aks-server-sp"
  ]
  type                       = "webapp/api"
  group_membership_claims    = "All"
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = false

  app_role {
    allowed_member_types = [
      "User",
      "Application",
    ]

    description  = "Admins can manage roles and perform all task actions"
    display_name = "Admin"
    is_enabled   = true
    value        = "Admin"
  }

  required_resource_access {
    # Windows Azure Active Directory API
    resource_app_id = "00000002-0000-0000-c000-000000000000"

    resource_access {
      # DELEGATED PERMISSIONS: "Sign in and read user profile":
      # 311a71cc-e848-46a1-bdf8-97ff7156d8e6
      id = "311a71cc-e848-46a1-bdf8-97ff7156d8e6"

      type = "Scope"
    }
  }

  required_resource_access {
    # MicrosoftGraph API
    resource_app_id = "00000003-0000-0000-c000-000000000000"

    # APPLICATION PERMISSIONS: "Read directory data":
    # 7ab1d382-f21e-4acd-a863-ba3e13f7da61
    resource_access {
      id   = "7ab1d382-f21e-4acd-a863-ba3e13f7da61"
      type = "Role"
    }

    # DELEGATED PERMISSIONS: "Sign in and read user profile":
    # e1fe6dd8-ba31-4d61-89e7-88639da4683d
    resource_access {
      id   = "e1fe6dd8-ba31-4d61-89e7-88639da4683d"
      type = "Scope"
    }

    # DELEGATED PERMISSIONS: "Read directory data":
    # 06da0dbc-49e2-44d2-8312-53f166ab848a
    resource_access {
      id   = "06da0dbc-49e2-44d2-8312-53f166ab848a"
      type = "Scope"
    }
  }

}

resource "azuread_application" "aks_client" {
  name = "${var.resource_group_name}-aks-client-adapp"
  reply_urls = [
    "https://${var.resource_group_name}-aks-client-sp"
  ]
  type = "native"

  required_resource_access {
    # AKS ad application server
    resource_app_id = azuread_application.aks_server.application_id

    resource_access {
      # Server app Oauth2 permissions id
      id   = lookup(azuread_application.aks_server.oauth2_permissions[0], "id")
      type = "Scope"
    }
  }
}
```

### Debug Output

```
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/<company>/<workspace>/runs/run-23vBjskNPxkQMso1

Waiting for the plan to start...

Terraform v0.12.26
Configuring remote state backend...
Initializing Terraform configuration...
2020/06/11 17:49:22 [DEBUG] Using modified User-Agent: Terraform/0.12.26 TFC/158668b279

Error: Invalid index

  on iam.tf line 199, in resource "azuread_application" "aks_client":
 199:       id   = lookup(azuread_application.aks_server.oauth2_permissions[0], "id")

This value does not have any indices.

Found errored.tfstate file, dumping contents...

{
  "version": 4,
  "terraform_version": "0.12.26",
  "serial": 3,
  "lineage": "d8fe5797-b624-81e0-80d4-0cd55195d849",
  "outputs": {},
  "resources": [
    {
      "mode": "data",
      "type": "azurerm_client_config",
      "name": "current",
      "provider": "provider.azurerm",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "client_id": "<azuread application client id>",
            "id": "2020-06-05 18:08:42.563001 +0000 UTC",
            "object_id": "<azuread application object id>",
            "subscription_id": "<azure subscription id>",
            "tenant_id": "<azure tenant id>",
            "timeouts": null
          }
        }
      ]
    },
    {
      "mode": "data",
      "type": "azurerm_subscription",
      "name": "current",
      "provider": "provider.azurerm",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "display_name": "Microsoft Azure Sponsorship",
            "id": "/subscriptions/<azure subscription id>",
            "location_placement_id": "Public_2014-09-01",
            "quota_id": "Sponsored_2016-01-01",
            "spending_limit": "Off",
            "state": "Enabled",
            "subscription_id": "<azure subscription id>",
            "tenant_id": "<azure tenant id>",
            "timeouts": null
          }
        }
      ]
    },
    {
      "mode": "managed",
      "type": "azuread_application",
      "name": "aks_client",
      "provider": "provider.azuread",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azuread_service_principal",
      "name": "aks_client",
      "provider": "provider.azuread",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azuread_service_principal",
      "name": "aks_cluster",
      "provider": "provider.azuread",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azuread_service_principal",
      "name": "aks_server",
      "provider": "provider.azuread",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azuread_service_principal_password",
      "name": "aks_client",
      "provider": "provider.azuread",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azuread_service_principal_password",
      "name": "aks_cluster_password",
      "provider": "provider.azuread",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azuread_service_principal_password",
      "name": "aks_server",
      "provider": "provider.azuread",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_application_gateway",
      "name": "core",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_key_vault",
      "name": "core",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_key_vault_certificate",
      "name": "default",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_kubernetes_cluster",
      "name": "core",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_kubernetes_cluster_node_pool",
      "name": "datanodes",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_kubernetes_cluster_node_pool",
      "name": "webnodes",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_public_ip",
      "name": "core_ingress",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_role_assignment",
      "name": "aks_cluster_contributor",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_role_assignment",
      "name": "aks_role_assignment",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_role_assignment",
      "name": "ingress_contributor",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_role_assignment",
      "name": "ingress_managed_identity_operator",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_role_assignment",
      "name": "ingress_network_contributor",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_role_assignment",
      "name": "ingress_reader",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_role_assignment",
      "name": "managed_identity_operator",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_role_assignment",
      "name": "network_contributor",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_subnet",
      "name": "core",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_subnet",
      "name": "core_ingress",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_user_assigned_identity",
      "name": "ingress",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "azurerm_virtual_network",
      "name": "core",
      "provider": "provider.azurerm",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "random_string",
      "name": "aks_client_password",
      "provider": "provider.random",
      "instances": []
    },
    {
      "mode": "managed",
      "type": "random_string",
      "name": "aks_cluster_password",
      "provider": "provider.random",
      "instances": [
        {
          "schema_version": 1,
          "attributes": {
            "id": "kgd3K?!STXjBkD\u0026B\u0026KAT]1\u0026c",
            "keepers": null,
            "length": 24,
            "lower": true,
            "min_lower": 1,
            "min_numeric": 1,
            "min_special": 1,
            "min_upper": 1,
            "number": true,
            "override_special": null,
            "result": "kgd3K?!STXjBkD\u0026B\u0026KAT]1\u0026c",
            "special": true,
            "upper": true
          },
          "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjEifQ=="
        }
      ]
    },
    {
      "mode": "managed",
      "type": "random_string",
      "name": "ask_server_password",
      "provider": "provider.random",
      "instances": []
    }
  ]
}
```

### Expected Behavior

- I can successfully run a plan that references the oauth permissions from an `azuread_application resource`

### Actual Behavior

- I am presented with this error if i attempt to run the plan using the remote execution with Terraform Cloud app. If i attempt to plan, using local execution but still storing the state in terraform cloud that works fine.
- Note this also worked before and suddenly stopped working

### Steps to Reproduce

1. configure terraform cloud workspace with remote execution
2. fill in required variables (azure and plan)
2. `terraform plan|apply`

### Important Factoids

- This worked before and stopped working over the course of this week.
- If this is run in a state that has already been successful, the state container the specified path with 1 item listed but the error is still thrown the same as an new state.

**Comment by manicminer** [comment] 2020-06-12 22:51
Hi @jalleyne, thanks for raising this issue. I believe the problem you're experiencing is due to a recent change which inadvertently broke some configurations. This was reported by another user in #265, in which there is a workaround. Can you give that a try and advise whether it works for you?

**Comment by manicminer** [comment] 2020-06-13 01:31
Duplicate of #265

**Comment by manicminer** [comment] 2020-06-30 02:28
Thanks again @jalleyne for raising this. As mentioned, there's a workaround in the linked issue which will allow you to address this property as a list. I'm going to close this one, but please feel free to comment further if you still encounter issues with this change.

**Closed by manicminer** 2020-06-30 02:28 UTC
Labels: bug, duplicate, feature/application, waiting-response
