### ISSUE TITLE
After version 0.10 - 0.11 it is not possible to use oauth2_permissions in later resources

### ISSUE THREAD

**Issue by lsrr** [terraform-providers/terraform-provider-azuread#300] opened 2020-08-11 09:03 UTC
### Terraform (and AzureAD Provider) Version
Tested with terraform v.12 and 13.
azuread provider v.0.9 works while v.10 and v.11 does not work

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
provider "azuread" {
  version = "0.9" # version 0.10 and 0.11 does not work
}

resource "azuread_application" "app" {
  name                       = "Application1"
  homepage                   = "https://myapplication1"
  identifier_uris            = ["https://myapplication1"]
  reply_urls                 = ["https://myapplication1"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = false
}

resource "local_file" "example_output" {
  content  = azuread_application.app.oauth2_permissions.0.id
  filename = "example.json"
}
```

### Expected Behavior

It should work as it did in version 0.9:
```
Other terraform output, then:
Plan: 2 to add, 0 to change, 0 to destroy.
```

### Actual Behavior

```
Error: Invalid index

  on main.tf line 16, in resource "local_file" "example_output":
  16:   content  = azuread_application.app.oauth2_permissions.0.id

This value does not have any indices.
```

### Steps to Reproduce

1. Copy the above snippet into editor of choice`
2. terraform plan
3. change azuread version to 0.10 or 0.11
4. Try again

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by lsrr** [comment] 2020-08-11 09:57
Update:

Found a workaround by using data after the resource have been created, then referencing data instead of the resource in the other resources:
```
provider "azuread" {
  version = "0.11"
}

resource "azuread_application" "app" {
  name                       = "Application1"
  homepage                   = "https://myapplication1"
  identifier_uris            = ["https://myapplication1"]
  reply_urls                 = ["https://myapplication1"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = false
}

# A data block referencing the newly created resource
data "azuread_application" "app" {
    application_id = azuread.app.application_id
}

resource "local_file" "example_output" {
  content  = data.azuread_application.app.oauth2_permissions.0.id
  filename = "example.json"
}
```

**Comment by manicminer** [comment] 2020-08-14 12:04
@lsrr Thanks for reporting this issue. I believe this was reported earlier in https://github.com/terraform-providers/terraform-provider-azuread/issues/265 shortly after the release of v0.10. There's a workaround in that thread where you can essentially assign the value to a new list and reference it with sequential indexes as you would have done with v0.9.0 and earlier.

Unfortunately this attribute will for the time being remain a set - due to the interaction with Terraform's handling of list items in configuration, and the nondeterministic ordering returned by the API we cannot reliably store either `app_role` or `oauth2_permissions` as lists.

**Comment by manicminer** [comment] 2020-08-14 12:04
Duplicate of #265

**Closed by manicminer** 2020-08-14 12:04 UTC
