### ISSUE TITLE
Support for Enterprise Application creation and properties

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-azuread#64] opened 2019-03-19 19:20 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like the provider to support creating and configuring the Azure Enterprise Application resources. These are service principals that are used as the Identity Provider for applications. It would be good to specify:

Logo and other properties
Assign and revoke users
configure the self-service settings

### New or Affected Resource(s)

??? - might be related to azuread_service_principal

**Comment by katbyte** [comment] 2019-05-23 23:35
Hi @mbrancato, 

This looks like a duplicate of #7. As such i am going to close it in favour of the older issue. If you believe i have done this i error please reopen this! thanks

**Closed by katbyte** 2019-05-23 23:35 UTC
